### PR TITLE
Set default permission mode

### PR DESCRIPTION
**Pull request by TrySound**
It works now!

### CODE REVIEW

**Comment by shinnn** [comment]
Can you elaborate about

* Why current version should be fixed?
* What kind of thing does this PR fix?

Example code is very welcome.

**Comment by kevva** [comment]
I really don't think this belongs here... but then again, I might be wrong.

**Comment by TrySound** [comment]
@shinnn @kevva When mode is broken by default all permissions denied. So I unzip and write files and can't change, read and execute them.

**Comment by shinnn** [comment]
Can you show us an example code and its `console.log` result?

**Comment by shinnn** [comment]
[As I said](https://github.com/kevva/decompress-unzip/pull/9#issuecomment-89829717), I still want this problem to be fixed in stat-mode.

**Comment by TrySound** [comment]
@shinnn That pull request was merged. And this is not problem of stat-mode.
```js
var Decompress = require('decompress'),
	vfs = require('vinyl-fs'),
	through = require('through2'),
	Mode = require('stat-mode');

new Decompress()
	.src('master.zip')
	.use(Decompress.zip({ strip: 1 }))
	.run(function (err, files) {
		files.forEach(function (file) {
			var m = new Mode(file.stat);
			console.log(m.toString(), file.path)
			var s = through.obj();
			s.end(file);
			s.pipe(vfs.dest('dest'));
		});
	});
```

```sh
---------- .gitignore
d--------- markup
---------- README.md
d--------- markup/modules
d--------- markup/modules/_template
-rwxr-xr-x markup/modules/_template/_template.html
d--------- markup/modules/footer
d--------- markup/modules/head
-rwxr-xr-x markup/modules/footer/footer.html
d--------- markup/modules/head/data
---------- markup/modules/head/data/data.js
d--------- markup/pages
-rwxr-xr-x markup/modules/head/head.html
-rwxr-xr-x markup/pages/_template.html
d--------- tars
-rwxr-xr-x markup/pages/index.html
d--------- tars/tasks
-rwxr-xr-x tars/tasks/compile-templates.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EACCES, chmod '/Workflow/sandbox/decompress/dest/markup/modules/head'
    at Error (native)

```

**Comment by TrySound** [comment]
@shinnn @kevva ?

**Comment by TrySound** [comment]
@kevva I was unconvincing?

**Comment by TrySound** [comment]
@shinnn @kevva up!

**Comment by TrySound** [comment]
@shinnn @kevva  Anybody is here?

**Comment by TrySound** [comment]
@shinnn @kevva  Guys, up!

**Comment by sindresorhus** [comment]
@TrySound 

> I was unconvincing?

Yes.

> And this is not problem of stat-mode.

Why is not? Explain why in words.

You should also explain why all this boilerplate in the PR is needed. Seems like it should be handled by `stat-mode` for me too.

**Comment by TrySound** [comment]
@sindresorhus There was a problem, that yauzl gave empty stat for file. We found solution how to detect directory. We used stat-mode to set file or directory mode. But for those empty mode permissions still were zeros. stat-mode is just setter, nothing more. So it was yauzl problem. I can't reproduce this problem, maybe it was fixed.

**Pull request closed without merging**
